spring:
  application:
    name: core-banking
  datasource:
    url: jdbc:postgresql://localhost:5432/core_banking_database
    username: banking_admin
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 10000

  rabbitmq:
    host: localhost
    port: 5672
    username: banking_admin
    password: password
    listener:
      simple:
        prefetch: 10
      cache:
        channel:
          size: 50

app:
  rabbitmq:
    exchange:
      core-events: core-banking-exchange