CREATE TABLE accounts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id UUID       NOT NULL UNIQUE,
    country     VARCHAR(2) NOT NULL,
    customer_id UUID       NOT NULL,
    created_at  TIMESTAMP  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP  NOT NULL DEFAULT now()
);