CREATE TABLE transactions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id   UUID           NOT NULL UNIQUE,
    account_id    BIGINT         NOT NULL,
    amount        NUMERIC(20, 8) NOT NULL,
    currency      VARCHAR(3)     NOT NULL,
    direction     VARCHAR(3)     NOT NULL,
    description   TEXT           NOT NULL,
    balance_after NUMERIC(20, 8) NOT NULL,
    created_at    TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP      NOT NULL DEFAULT now(),

    CONSTRAINT fk_transactions_accounts FOREIGN KEY (account_id) REFERENCES accounts (id)
);

CREATE INDEX idx_transactions_account_id ON transactions (account_id);